# File: /Dockerfile
# Description: Dockerfile for Geaux Academy application using the Node.js devcontainer image.
# Author: [Your Name]
# Created: [Date]

# Use Node.js as the base image
FROM node:18-slim

# Set working directory
WORKDIR /app

# Add build arguments for all environment variables
ARG AGENTOPS_API_KEY
ARG ANTHROPIC_API_KEY
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG DATABASE_URL
ARG DB_PASSWORD
ARG DB_USERNAME
ARG GROQ_API_KEY
ARG OPENAI_API_KEY
ARG REPLICATE
ARG SERPER_SEARCH
ARG SUPERABASE_SERVICE_KEY
ARG TWILIO_AUTH_TOKEN
ARG VITE_CHESHIRE_ADMIN_PASSWORD
ARG VITE_CHESHIRE_ADMIN_USERNAME
ARG VITE_CHESHIRE_API_TOKEN
ARG VITE_CHESHIRE_API_TOKEN_TYPE
ARG VITE_CHESHIRE_API_URL
ARG VITE_CHESHIRE_DEBUG
ARG VITE_FIREBASE_API_KEY
ARG VITE_FIREBASE_APP_ID
ARG VITE_FIREBASE_AUTH_DOMAIN
ARG VITE_FIREBASE_DATABASE_URL
ARG VITE_FIREBASE_MEASUREMENT_ID
ARG VITE_FIREBASE_MESSAGING_SENDER_ID
ARG VITE_FIREBASE_PROJECT_ID
ARG VITE_FIREBASE_STORAGE_BUCKET
ARG VITE_OPENAI_API_KEY
ARG WEBSITE_URL

# Set environment variables from build arguments
ENV AGENTOPS_API_KEY=$AGENTOPS_API_KEY \
    ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY \
    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
    AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    DATABASE_URL=$DATABASE_URL \
    DB_PASSWORD=$DB_PASSWORD \
    DB_USERNAME=$DB_USERNAME \
    GROQ_API_KEY=$GROQ_API_KEY \
    OPENAI_API_KEY=$OPENAI_API_KEY \
    REPLICATE=$REPLICATE \
    SERPER_SEARCH=$SERPER_SEARCH \
    SUPERABASE_SERVICE_KEY=$SUPERABASE_SERVICE_KEY \
    TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN \
    VITE_CHESHIRE_ADMIN_PASSWORD=$VITE_CHESHIRE_ADMIN_PASSWORD \
    VITE_CHESHIRE_ADMIN_USERNAME=$VITE_CHESHIRE_ADMIN_USERNAME \
    VITE_CHESHIRE_API_TOKEN=$VITE_CHESHIRE_API_TOKEN \
    VITE_CHESHIRE_API_TOKEN_TYPE=$VITE_CHESHIRE_API_TOKEN_TYPE \
    VITE_CHESHIRE_API_URL=$VITE_CHESHIRE_API_URL \
    VITE_CHESHIRE_DEBUG=$VITE_CHESHIRE_DEBUG \
    VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY \
    VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID \
    VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN \
    VITE_FIREBASE_DATABASE_URL=$VITE_FIREBASE_DATABASE_URL \
    VITE_FIREBASE_MEASUREMENT_ID=$VITE_FIREBASE_MEASUREMENT_ID \
    VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID \
    VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID \
    VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET \
    VITE_OPENAI_API_KEY=$VITE_OPENAI_API_KEY \
    WEBSITE_URL=$WEBSITE_URL

# Copy package files
COPY package*.json ./
COPY functions/package*.json ./functions/

# Install dependencies
RUN npm ci
RUN cd functions && npm ci

# Copy project files
COPY . .

# Build the application
RUN npm run build

# Expose port
EXPOSE 3000

# Start command
CMD ["npm", "start"]
