blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: https://github.com/GeauxAcademy/GA-MVP/issues/new?template=bug_report.md
    about: Report a bug to help us improve
  - name: Feature Request
    url: https://github.com/GeauxAcademy/GA-MVP/issues/new?template=feature_request.md
    about: Suggest a new feature or enhancement
  - name: Custom Issue
    url: https://github.com/GeauxAcademy/GA-MVP/issues/new?template=custom.md
    about: Create a custom issue for other types of requests
