name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci --legacy-peer-deps

    - name: Run linter
      run: npm run lint

    - name: Run tests
      run: npm test

    - name: Build
      run: npm run build

    - name: Install Firebase CLI
      if: github.ref == 'refs/heads/main'
      run: npm install -g firebase-tools

    - name: Firebase Authentication
      if: github.ref == 'refs/heads/main'
      run: firebase login:ci --no-localhost

    - name: Deploy to Firebase
      if: github.ref == 'refs/heads/main'
      run: |
        firebase use default
        firebase deploy --token "$FIREBASE_TOKEN" --non-interactive
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
